name: card_swiper
description: swiper/carousel for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 2.0.3
homepage: https://github.com/TheAnkurPanchani/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=0.1.4"

dev_dependencies:
  flutter_lints_plus: ^1.0.1
  flutter_test:
    sdk: flutter

flutter:
