name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 2.0.0
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/jzoom/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=0.1.4 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: '^1.11.0'

flutter:
